import groovy.json.JsonOutput
import groovy.json.JsonSlurper

plugins {
    id('java')
    id('eclipse')
    id('idea')
    id('maven-publish')
    // https://projects.neoforged.net/neoforged/ModDevGradle
    id('net.neoforged.moddev') version('2.0.78')
}

tasks.named('wrapper', Wrapper) {
    //Define wrapper values here so as to not have to always do so when updating gradlew.properties
    gradleVersion = '8.13'
    distributionType = Wrapper.DistributionType.BIN
}

project.base.archivesName = project.archives_base_name
version = "neoforge-${minecraft_version}-${mod_version}"
group = project.maven_group

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of("${java_version}"))
        vendor.set(JvmVendorSpec.JETBRAINS)
    }
}

println("Java: ${System.getProperty 'java.version'}, JVM: ${System.getProperty 'java.vm.version'} (${System.getProperty 'java.vendor'}), Arch: ${System.getProperty 'os.arch'}")

neoForge {
    version = neo_version

    accessTransformers.from(file('src/main/resources/META-INF/accesstransformer.cfg'))

    mods {
        wildfire_gender {
            sourceSet(sourceSets.main)
        }
    }
}

neoForge.runs {
    configureEach {
        if (project.hasProperty('forge_force_ansi')) {
            //Force ansi if declared as a gradle variable, as the auto detection doesn't detect IntelliJ properly
            // or eclipse's plugin that adds support for ansi escape in console
            systemProperties.put('terminal.ansi', (String) property('forge_force_ansi'))
        }

        //if the selected toolchain is a JBR, enable DCEVM
        if (javaToolchains.launcherFor(java.toolchain).map { it.metadata.vendor }.getOrElse('').contains('JetBrains')) {
            jvmArguments.addAll('-XX:+IgnoreUnrecognizedVMOptions', '-XX:+AllowEnhancedClassRedefinition')
        }

        sourceSet = sourceSets.main
    }
    client {
        client()
        //Note: To enable logging into the client account, set the mc_devlogin property to true in your gradle user home
        if (findProperty('mc_devlogin') ?: false) {
            //If the property is present and set to true, enable dev login
            devLogin = true
        }
    }
    clientAlt {
        client()
        // Force a different username in case devlogin is not enabled for the main run
        programArguments.addAll((String[]) ['--username', 'AltDev'])
    }
    server {
        server()
    }
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation('org.junit.jupiter:junit-jupiter:5.10.2')
    testRuntimeOnly('org.junit.platform:junit-platform-launcher')
}

tasks.named('test', Test) {
    useJUnitPlatform()
    testLogging {
        events 'failed', 'passed', 'skipped'
        exceptionFormat 'full'
    }
}

def replaceResources = tasks.register('replaceResources', Copy) {
    def versionProperties = ['file': ['jarVersion': mod_version], 'mc_version': minecraft_version_range, 'neo_version': neo_version_range,
                             'loader_version': loader_version_range]
    inputs.properties(versionProperties)
    def modsToml = copySpec {
        from(sourceSets.main.resources) {
            include('META-INF/neoforge.mods.toml')
            expand(versionProperties)
        }
    }
    //Copy it into the build dir
    with(modsToml)
    into(layout.buildDirectory.dir('resources/main'))
    //If IntelliJ's output dir exists, copy it there as well
    if (new File("$rootDir/out/production/").exists()) {
        copy {
            with(modsToml)
            into("$rootDir/out/production/")
        }
    }
    //If Eclipse's output dir exists, copy it there as well
    if (new File("$rootDir/bin/main/").exists()) {
        copy {
            with(modsToml)
            into("$rootDir/bin/main/")
        }
    }
}

//Set the various variables/settings for the different process resources tasks
tasks.named('processResources', ProcessResources) {
    duplicatesStrategy = DuplicatesStrategy.FAIL
    exclude('META-INF/neoforge.mods.toml')
    finalizedBy(replaceResources)
    def files = fileTree(dir: outputs.files.asPath, includes: ['**/*.json', '**/*.mcmeta'])
    doLast {
        for (def file : files) {
            file.text = JsonOutput.toJson(new JsonSlurper().parse(file))
        }
    }
}

//Make the various classes tasks depend on the corresponding replaceResources tasks in addition to the default processResources tasks they depend on
tasks.named('classes') { dependsOn(replaceResources) }

// Example for how to get properties into the manifest for reading at runtime.
tasks.named('jar', Jar) {
    duplicatesStrategy = DuplicatesStrategy.FAIL
    manifest.attributes([
            'Specification-Title'     : project.name,
            'Specification-Vendor'    : 'Wildfire',
            'Specification-Version'   : "${mod_version}",
            'Implementation-Title'    : project.name,
            'Implementation-Version'  : "${mod_version}",
            'Implementation-Vendor'   : 'Wildfire',
            'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
            'Automatic-Module-Name'   : 'wildfire_gender'
    ])
}

publishing {
    publications { PublicationContainer publicationContainer ->
        publicationContainer.register('mavenJava', MavenPublication) { MavenPublication publication ->
            artifact(jar)
        }
    }
    repositories {
        maven {
            url = "file://${project.projectDir}/mcmodsrepo"
        }
    }
}

tasks.withType(JavaCompile).configureEach({
    options.encoding = 'UTF-8'
    options.compilerArgs.addAll(['-Xmaxerrs', '100000'])
})

tasks.withType(Javadoc).configureEach({
    options.encoding = 'UTF-8'
    options.tags = [
            'apiNote:a:<em>API Note:</em>',
            'implSpec:a:<em>Implementation Requirements:</em>',
            'implNote:a:<em>Implementation Note:</em>'
    ]
})
